<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3store2\models\base;

use Yii;


/**
 * This is the base-model class for table "store2_store".
 *
 * @property integer $id
 * @property integer $company_id
 * @property string $name
 * @property string $address
 * @property integer $active
 *
 * @property \d3yii2\d3store2\models\Store2Stack[] $store2Stacks
 * @property string $aliasModel
 */
abstract class Store2Store extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'store2_store';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['company_id'], 'required'],
            'tinyint Signed' => [['active'], 'integer', 'min' => -128, 'max' => 127],
            'smallint Unsigned' => [['id', 'company_id'], 'integer', 'min' => 0, 'max' => 65535],
            [['name'], 'string', 'max' => 50],
            [['address'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('store2', 'ID'),
            'company_id' => Yii::t('store2', 'Company ID'),
            'name' => Yii::t('store2', 'Store Name'),
            'address' => Yii::t('store2', 'Store Address'),
            'active' => Yii::t('store2', 'Active'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStore2Stacks()
    {
        return $this->hasMany(\d3yii2\d3store2\models\Store2Stack::className(), ['store_id' => 'id']);
    }


}
