<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3store2\models\base;

use d3system\dictionaries\SysModelsDictionary;
use Yii;


/**
 * This is the base-model class for table "store2_tran_ref".
 *
 * @property integer $id
 * @property integer $transaction_id
 * @property integer $model_id
 * @property integer $model_record_id
 *
 * @property \d3yii2\d3store2\models\SysModels $model
 * @property \d3yii2\d3store2\models\Store2Transaction $transaction
 * @property string $aliasModel
 */
abstract class Store2TranRef extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'store2_tran_ref';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['transaction_id', 'model_id', 'model_record_id'], 'required'],
            'tinyint Unsigned' => [['model_id'], 'integer', 'min' => 0, 'max' => 255],
            'smallint Unsigned' => [['model_record_id'], 'integer', 'min' => 0, 'max' => 65535],
            'integer Unsigned' => [['id', 'transaction_id'], 'integer', 'min' => 0, 'max' => 4294967295],
            [['transaction_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3store2\models\Store2Transaction::className(), 'targetAttribute' => ['transaction_id' => 'id']],
            [['model_id'], 'in', 'range' => array_keys(SysModelsDictionary::getClassList())]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('store2', 'ID'),
            'transaction_id' => Yii::t('store2', 'Transaction ID'),
            'model_id' => Yii::t('store2', 'Model ID'),
            'model_record_id' => Yii::t('store2', 'Model Record ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getModel()
    {
        return $this->hasOne(\d3yii2\d3store2\models\SysModels::className(), ['id' => 'model_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransaction()
    {
        return $this->hasOne(\d3yii2\d3store2\models\Store2Transaction::className(), ['id' => 'transaction_id']);
    }


}
