<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3store2\models\base;

use Yii;


/**
 * This is the base-model class for table "store2_stack".
 *
 * @property integer $id
 * @property integer $store_id
 * @property string $name
 * @property string $notes
 * @property integer $active
 *
 * @property \d3yii2\d3store2\models\Store2Store $store
 * @property \d3yii2\d3store2\models\Store2Transaction[] $store2Transactions
 * @property string $aliasModel
 */
abstract class Store2Stack extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'store2_stack';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['store_id'], 'required'],
            'tinyint Unsigned' => [['active'], 'integer', 'min' => 0, 'max' => 255],
            'smallint Unsigned' => [['id', 'store_id'], 'integer', 'min' => 0, 'max' => 65535],
            [['notes'], 'string'],
            [['name'], 'string', 'max' => 255],
            [['store_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3store2\models\Store2Store::className(), 'targetAttribute' => ['store_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('store2', 'ID'),
            'store_id' => Yii::t('store2', 'Store'),
            'name' => Yii::t('store2', 'Stack name'),
            'notes' => Yii::t('store2', 'Notes'),
            'active' => Yii::t('store2', 'Active'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStore()
    {
        return $this->hasOne(\d3yii2\d3store2\models\Store2Store::className(), ['id' => 'store_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStore2Transactions()
    {
        return $this->hasMany(\d3yii2\d3store2\models\Store2Transaction::className(), ['stack_id' => 'id']);
    }


}
